[
  { "id": "P001", "nombre": "Lápiz Azul", "cantidad": 12 },
  { "id": "P002", "nombre": "Cuaderno Rayado", "cantidad": 20 },
  { "id": "P003", "nombre": "Bolígrafo Negro", "cantidad": 15 },
  { "id": "P004", "nombre": "Borrador", "cantidad": 30 },
  { "id": "P005", "nombre": "Resaltador Amarillo", "cantidad": 8 },
  { "id": "P006", "nombre": "Corrector Líquido", "cantidad": 5 },
  { "id": "P007", "nombre": "Regla 30cm", "cantidad": 10 },
  { "id": "P008", "nombre": "Tijeras Escolares", "cantidad": 7 },
  { "id": "P009", "nombre": "Pegamento en Barra", "cantidad": 9 },
  { "id": "P010", "nombre": "Carpeta Plástica", "cantidad": 18 },
  { "id": "P011", "nombre": "Marcador Permanente", "cantidad": 6 },
  { "id": "P012", "nombre": "Lápices de Colores", "cantidad": 14 },
  { "id": "P013", "nombre": "Libreta de Notas", "cantidad": 22 },
  { "id": "P014", "nombre": "Estuche Escolar", "cantidad": 13 },
  { "id": "P015", "nombre": "Compás", "cantidad": 4 },
  { "id": "P016", "nombre": "Papel Bond A4", "cantidad": 25 },
  { "id": "P017", "nombre": "Folder Manila", "cantidad": 11 },
  { "id": "P018", "nombre": "Cinta Adhesiva", "cantidad": 16 },
  { "id": "P019", "nombre": "Cartulina Blanca", "cantidad": 19 },
  { "id": "P020", "nombre": "Cuaderno Cuadriculado", "cantidad": 17 }
]
